# config/packages/debug.yaml
when@dev:
    debug:
        dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"

    # Si VAR_DUMPER_SERVER n'est pas d√©fini, utiliser la sortie standard
    # Lancer avec: symfony server:dump

when@test:
    debug:
        dump_destination: null
