# config/packages/translation.yaml
# Configuration des traductions
framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
            - en
