# Render.com Blueprint
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: taskmanager
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /login
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DEFAULT_URI
        value: "https://taskmanager-zv0a.onrender.com"
      - key: TRUSTED_PROXIES
        value: "127.0.0.1,REMOTE_ADDR"
      - key: TRUSTED_HOSTS
        value: "^.*\\.onrender\\.com$"
